Repository atk4/core, pull requests merged in 2021-04, with the labels that each got.

#308 Fix missing use
  phpstan.neon.dist
  src/AtkPhpunit/TestCase.php
Labels: bug

#227 Remove trait identification property
  phpstan.neon.dist
  src/AppScopeTrait.php
  src/CollectionTrait.php
  src/ConfigTrait.php
  src/ContainerTrait.php
  src/DebugTrait.php
  src/DiContainerTrait.php
  src/DynamicMethodTrait.php
  src/ExceptionRenderer/RendererAbstract.php
  src/Factory.php
  src/FactoryTrait.php
  src/HookTrait.php
  src/InitializerTrait.php
  src/NameTrait.php
  src/SessionTrait.php
  src/StaticAddToTrait.php
  src/TrackableTrait.php
  src/TraitUtil.php
  src/TranslatableTrait.php
  tests/ContainerTraitTest.php
  tests/StaticAddToTest.php
  tests/TraitUtilTest.php
Labels: BC-break, RTM

#312 Migrate missed "_trackableTrait" usage
  src/ExceptionRenderer/RendererAbstract.php
Labels: RTM

#283 Update release builder
  .github/workflows/build-docs.yml
  .github/workflows/build-release.yml
  .github/workflows/bundler.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-unit.yml
  composer.json
Labels: RTM
